Repository Volgarenok/spbspu-labs-2025-aads-classes-a, pull requests merged in 2025-03, with the labels that each got.

#40 maslov.aleksey/K3
  maslov.aleksey/K3/main.cpp
Labels: 2 out of 2, fine

#37 lanovenko.ivan/K3
  lanovenko.ivan/K3/main.cpp
Labels: 2 out of 2

#18 guseynov.guseyn/K2
  guseynov.guseyn/K2/main.cpp
Labels: 1 out of 2, fine

#35 shramko.maksim/K3
  shramko.maksim/K3/main.cpp
Labels: 2 out of 2, fine

#52 rychkov.mihail/K6
  rychkov.mihail/K6/main.cpp
Labels: 2 out of 2, fine

#48 mozhegova.maria/K6
  mozhegova.maria/K6/main.cpp
Labels: 2 out of 2, fine

#54 maslov.aleksey/K6
  maslov.aleksey/K6/main.cpp
Labels: 2 out of 2, fine

#16 balashov.dima/K1
  balashov.dima/K1/main.cpp
Labels: 1 out of 2, trash, actor

#32 hismatova.elizaveta/K3
  hismatova.elizaveta/K3/main.cpp
Labels: 1 out of 2, trash

#34 sharifullina.sofia/K3
  sharifullina.sofia/sharifullina.sofia/K3/main.cpp
Labels: 1 out of 2, trash, actor
