Repository Volgarenok/spbspu-labs-2025-aads-classes-a, pull requests merged in 2025-04, with the labels that each got.

#46 lebedev.alexandr/K6
  lebedev.alexandr/K6/main.cpp
Labels: 2 out of 2, fine

#55 tkach.danil/K6
  tkach.danil/K6/main.cpp
Labels: 2 out of 2, fine

#49 finaev.alexey/K6
  finaev.alexey/K6/main.cpp
Labels: 2 out of 2, fine

#47 lanovenko.ivan/K6
  lanovenko.ivan/K6/main.cpp
Labels: 1 out of 2, fine

#50 hismatova.elizaveta/K6
  hismatova.elizaveta/K6/main.cpp
Labels: 2 out of 2, fine

#56 smirnov.alexandr/K6
  smirnov.alexandr/K6/main.cpp
Labels: 2 out of 2
