Repository Volgarenok/spbspu-labs-2025-aads-classes-a, pull requests merged in 2025-02, with the labels that each got.

#15 tkach.danil/K1
  tkach.danil/K1/list.hpp
  tkach.danil/K1/main.cpp
Labels: 2 out of 2, fine

#7 mozhegova.maria/K1
  mozhegova.maria/K1/main.cpp
Labels: 2 out of 2, fine

#6 petrov.nikita/K1
  petrov.nikita/K1/main.cpp
Labels: 2 out of 2, fine

#14 rychkov.mihail/K1
  rychkov.mihail/K1/bi_list.cpp
  rychkov.mihail/K1/bi_list.hpp
  rychkov.mihail/K1/main.cpp
Labels: 2 out of 2

#3 sharifullina.sofia/K1
  sharifullina.sofia/K1/main.cpp
Labels: 2 out of 2, fine

#11 maslov.aleksey/K1
  maslov.aleksey/K1/main.cpp
Labels: 2 out of 2, fine

#1 hismatova.elizaveta/K1
  hismatova.elizaveta/K1/main.cpp
Labels: 2 out of 2, fine

#10 finaev.alexey/K1
  finaev.alexey/K1/main.cpp
Labels: 1 out of 2

#12 lebedev.alexandr/K1
  lebedev.alexandr/K1/main.cpp
Labels: 2 out of 2

#9 lanovenko.ivan/K1
  lanovenko.ivan/K1/bilist.hpp
  lanovenko.ivan/K1/main.cpp
Labels: 1 out of 2, fine

#17 guseynov.guseyn/K1
  guseynov.guseyn/K1/main.cpp
Labels: 1 out of 2, fine

#19 shramko.maksim/K2
  shramko.maksim/K2/main.cpp
Labels: 2 out of 2, fine

#22 rychkov.mihail/K2
  rychkov.mihail/K2/fwd_list.cpp
  rychkov.mihail/K2/fwd_list.hpp
  rychkov.mihail/K2/main.cpp
Labels: 2 out of 2, fine

#29 finaev.alexey/K2
  finaev.alexey/K2/main.cpp
Labels: 2 out of 2

#27 mozhegova.maria/K2
  mozhegova.maria/K2/main.cpp
Labels: 2 out of 2

#26 tkach.danil/K2
  tkach.danil/K2/main.cpp
Labels: 2 out of 2, fine

#25 smirnov.alexandr/K2
  smirnov.alexandr/K2/main.cpp
Labels: 2 out of 2, fine

#24 maslov.aleksey/K2
  maslov.aleksey/K2/main.cpp
Labels: 2 out of 2, fine

#23 petrov.nikita/K2
  petrov.nikita/K2/main.cpp
Labels: 2 out of 2, fine

#21 hismatova.elizaveta/K2
  hismatova.elizaveta/K2/main.cpp
Labels: 2 out of 2, fine

#20 lanovenko.ivan/K2
  lanovenko.ivan/K2/main.cpp
Labels: 2 out of 2, fine

#28 lebedev.alexandr/K2
  lebedev.alexandr/K2/main.cpp
Labels: 1 out of 2, fine

#43 tkach.danil/K3
  tkach.danil/K3/main.cpp
Labels: 2 out of 2, fine

#39 rychkov.mihail/K3
  rychkov.mihail/K3/main.cpp
Labels: 2 out of 2, fine

#42 petrov.nikita/K3
  petrov.nikita/K3/main.cpp
Labels: 2 out of 2, fine, actor

#36 smirnov.alexandr/K3
  smirnov.alexandr/K3/main.cpp
Labels: 2 out of 2, fine
